#
#  Author: Hari Sekhon
#  Date: 2025-12-17 23:07:35 -0600 (Wed, 17 Dec 2025)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Knowledge-Base
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#       Markdown Links
# ============================================================================ #

# Check all markdown [Name](url) links actually contain a URL in between the (brackets)
# as it's common to copy and paste when the clipboard did not catch the link

---
name: Markdown Links

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .github/scripts/check_markdown_links.sh
      - .github/workflows/markdown_links.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
      - .github/scripts/check_markdown_links.sh
      - .github/workflows/markdown_links.yaml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  markdown-links:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Markdown Links
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        #name: Git Checkout  # better to show the action@version
        with:
          submodules: 'true'  # requires Git 2.18+ to be installed first

      - name: Check all Markdown Links contain URLs
        run: .github/scripts/check_markdown_links.sh
